### PR TITLE
Create config-fermat.sh

### PR DESCRIPTION
**Pull request by xanthe-cat**
Shell-script cowritten by Teal Dulcet and Catherine Cowie to configure Mlucas for production work on Fermat numbers, by testing the Fermat modular squaring code at various FFT lengths over 10000 iterations, on the appropriate Fermat number for that size, which then writes timing and radix set data to fermat.cfg in the Mlucas executable directory Mlucas/obj. A log file config-fermat.log records the Mlucas output. During installation a copy of this script should be copied to the Mlucas executable directory.

### CODE REVIEW

**Comment by xanthe-cat** [comment]
Hi Teal,
I’m happy with the script as is now (I don’t think any further micro-optimisations are desirable unless there are actual bug issues raised). I did change the log file config.fermat.log to use the hyphen seeing as this file is called config-fermat.sh.
I imagine this file might better be located in the src directory (even though it’s not part of building Mlucas) and the makemake.sh script simply duplicates it into whatever obj directory it’s making as part of the build.

**Review by tdulcet — APPROVED** [review]
Thank you for the PR and for all your work on this script! I can merge it as soon as you have had a chance to review my changes. You may want to review the CI output as well, just click on the "Checks" tab -> any of the Mlucas Linux or macOS jobs -> the "Script" step and then scroll down to the very bottom to see the output from this script.

I do not believe we would need to duplicate the script, as users should be able to just run something like this (similar to what I did in the CI):
```bash
cd obj && bash ../config-fermat.sh [Mlucas args]...
```

**Review by xanthe-cat — COMMENTED** [review]
All looks good; if the script is going to reside in the main directory the comment at L43 should perhaps use the example of e.g. bash ../config-fermat.sh but I can live with this.

**Comment by tdulcet** [comment]
I updated your comment as requested. Please feel free to make any further changes. I will give @ldesnogu a chance to review this if they want, before merging it.

**Pull request merged**
